# Generated by Django 4.1.6 on 2024-02-27 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('skills', models.CharField(max_length=500)),
                ('companies', models.CharField(max_length=255)),
                ('certification', models.CharField(max_length=255)),
                ('experience', models.CharField(max_length=255)),
                ('college_name', models.CharField(max_length=255)),
                ('extracted_data', models.TextField(blank=True)),
            ],
        ),
    ]
